import { Component } from '@angular/core';

@Component({
  selector: 'app-trujillo',
  imports: [],
  templateUrl: './trujillo.component.html',
  styleUrl: './trujillo.component.css',
})
export class TrujilloComponent {
  rutas = [
    {
      nombre: 'Ruta al Castillo de Trujillo',
      salida: 'Plaza Mayor',
      llegada: 'Castillo de Trujillo',
      km: 3,
      dificultad: 'Fácil',
      duracion: '1,5 h',
      tipo: 'Ida y vuelta',
      imagen: 'images/trujillo/ruta-castillo-trujillo.jpg',
      maps: 'https://www.google.com/maps/search/Castillo+de+Trujillo',
    },
    {
      nombre: 'Ruta de los Berrocales',
      salida: 'Trujillo',
      llegada: 'Zona de berrocales',
      km: 6,
      dificultad: 'Fácil',
      duracion: '2 h',
      tipo: 'Circular',
      imagen: 'images/trujillo/berrocal.jpg',
      maps: 'https://www.google.com/maps/search/Berrocales+Trujillo',
    },
    {
      nombre: 'Ruta del Arroyo Magasca',
      salida: 'Huertas de Ánimas',
      llegada: 'Arroyo Magasca',
      km: 7,
      dificultad: 'Fácil',
      duracion: '2,5 h',
      tipo: 'Lineal',
      imagen: 'images/trujillo/magasca.jpg',
      maps: 'https://www.google.com/maps/search/Arroyo+Magasca',
    },
    {
      nombre: 'Sendero de Santa Cruz',
      salida: 'Trujillo',
      llegada: 'Ermita de Santa Cruz',
      km: 5,
      dificultad: 'Fácil',
      duracion: '2 h',
      tipo: 'Circular',
      imagen: 'images/trujillo/sendero-santaCruz.jpg',
      maps: 'https://www.google.com/maps/search/Ermita+de+Santa+Cruz+Trujillo',
    },
    {
      nombre: 'Ruta de la Dehesa Extremeña',
      salida: 'Trujillo',
      llegada: 'Dehesas del entorno',
      km: 9,
      dificultad: 'Media',
      duracion: '3 h',
      tipo: 'Circular',
      imagen: 'images/trujillo/dehesa-extremeña.jpg',
      maps: 'https://www.google.com/maps/search/Dehesa+Trujillo',
    },
    {
      nombre: 'Ruta del Río Tamuja',
      salida: 'Aldea del Obispo',
      llegada: 'Río Tamuja',
      km: 8,
      dificultad: 'Media',
      duracion: '3 h',
      tipo: 'Lineal',
      imagen: 'images/trujillo/rita-tamatuja.jpg',
      maps: 'https://www.google.com/maps/search/Rio+Tamuja',
    },
    {
      nombre: 'Ruta de los Miradores de Trujillo',
      salida: 'Casco histórico',
      llegada: 'Miradores naturales',
      km: 4,
      dificultad: 'Fácil',
      duracion: '1,5 h',
      tipo: 'Circular',
      imagen: 'images/trujillo/miradores-trujillo.jpg',
      maps: 'https://www.google.com/maps/search/Miradores+de+Trujillo',
    },
    {
      nombre: 'Ruta del Berrocal de Huertas de Ánimas',
      salida: 'Huertas de Ánimas',
      llegada: 'Berrocal granítico',
      km: 6,
      dificultad: 'Fácil',
      duracion: '2 h',
      tipo: 'Circular',
      imagen: 'images/trujillo/huertas-de-animas.jpg',
      maps: 'https://www.google.com/maps/search/Huertas+de+Animas',
    },
    {
      nombre: 'Sendero del Tajo Trujillano',
      salida: 'Entorno del Tajo',
      llegada: 'Miradores del río',
      km: 10,
      dificultad: 'Media',
      duracion: '3,5 h',
      tipo: 'Lineal',
      imagen: 'images/trujillo/tajo-trujillo.webp',
      maps: 'https://www.google.com/maps/search/Rio+Tajo+Trujillo',
    },
    {
      nombre: 'Ruta Histórica Trujillana',
      salida: 'Plaza Mayor',
      llegada: 'Casco monumental',
      km: 3,
      dificultad: 'Fácil',
      duracion: '1,5 h',
      tipo: 'Circular',
      imagen: 'images/trujillo/casco-historico.jpg',
      maps: 'https://www.google.com/maps/search/Plaza+Mayor+Trujillo',
    },
  ];
}
