import { Component } from '@angular/core';

@Component({
  selector: 'app-la-vera',
  standalone: true,
  imports: [],
  templateUrl: './la-vera.component.html',
  styleUrls: ['./la-vera.component.css'], // 👈 AQUÍ
})
export class LaVeraComponent {
  rutas = [
    {
      nombre: 'Garganta de Cuartos',
      salida: 'Losar de la Vera',
      llegada: 'Cascada de Cuartos',
      km: 7,
      dificultad: 'Fácil',
      duracion: '2 h',
      tipo: 'Ida y vuelta',
      imagen: 'images/vera/garganta_de_cuartos.jpg',
      maps: 'https://www.google.com/maps/search/Garganta+de+Cuartos',
    },

    {
      nombre: 'Ruta de las Gargantas',
      salida: 'Madrigal de la Vera',
      llegada: 'Garganta de Alardos',
      km: 9,
      dificultad: 'Media',
      duracion: '3 h',
      tipo: 'Circular',
      imagen: 'images/vera/garganta-alardos.jpg',
      maps: 'https://www.google.com/maps/search/Garganta+de+Alardos',
    },
    {
      nombre: 'Ruta Carlos V',
      salida: 'Cuacos de Yuste',
      llegada: 'Jarandilla de la Vera',
      km: 10,
      dificultad: 'Media',
      duracion: '3,5 h',
      tipo: 'Lineal',
      imagen: 'images/vera/ruta-carlosV.jpg',
      maps: 'https://www.google.com/maps/search/Ruta+Carlos+V+Yuste',
    },
    {
      nombre: 'Garganta Mayor',
      salida: 'Garganta la Olla',
      llegada: 'Piscinas naturales',
      km: 6,
      dificultad: 'Fácil',
      duracion: '2 h',
      tipo: 'Circular',
      imagen: 'images/vera/garganta-mayor.jpg',
      maps: 'https://www.google.com/maps/search/Garganta+la+Olla',
    },
    {
      nombre: 'Sendero del Trabuquete',
      salida: 'Guijo de Santa Bárbara',
      llegada: 'Mirador del Trabuquete',
      km: 8,
      dificultad: 'Media',
      duracion: '3 h',
      tipo: 'Ida y vuelta',
      imagen: 'images/vera/Sendero-del-trabuquete.jpg',
      maps: 'https://www.google.com/maps/search/Guijo+de+Santa+Barbara',
    },
    {
      nombre: 'Ruta de las Nogaledas',
      salida: 'Navaconcejo',
      llegada: 'Cascadas de las Nogaledas',
      km: 5,
      dificultad: 'Fácil',
      duracion: '2 h',
      tipo: 'Circular',
      imagen: 'images/vera/Ruta-de-las-nogaledas.jpg',
      maps: 'https://www.google.com/maps/search/Cascadas+de+las+Nogaledas',
    },
    {
      nombre: 'Ruta del Emperador',
      salida: 'Cuacos de Yuste',
      llegada: 'Monasterio de Yuste',
      km: 4,
      dificultad: 'Fácil',
      duracion: '1,5 h',
      tipo: 'Ida y vuelta',
      imagen: 'images/vera/ruta-del-emperador.webp',
      maps: 'https://www.google.com/maps/search/Monasterio+de+Yuste',
    },
    {
      nombre: 'Garganta de Minchones',
      salida: 'Villanueva de la Vera',
      llegada: 'Charcos naturales',
      km: 7,
      dificultad: 'Media',
      duracion: '2,5 h',
      tipo: 'Circular',
      imagen: 'images/vera/garganta-minchones.jpg',
      maps: 'https://www.google.com/maps/search/Villanueva+de+la+Vera',
    },
    {
      nombre: 'Ruta del Piornal',
      salida: 'Piornal',
      llegada: 'Miradores del Valle',
      km: 11,
      dificultad: 'Media',
      duracion: '4 h',
      tipo: 'Circular',
      imagen: 'images/vera/ruta-piornal.jpg',
      maps: 'https://www.google.com/maps/search/Piornal',
    },
    {
      nombre: 'Sendero del Tiétar',
      salida: 'Talaveruela',
      llegada: 'Río Tiétar',
      km: 6,
      dificultad: 'Fácil',
      duracion: '2 h',
      tipo: 'Lineal',
      imagen: 'images/vera/sendero-del-tietar.jpg',
      maps: 'https://www.google.com/maps/search/Rio+Tietar',
    },
  ];
}
